### ISSUE TITLE
Mixin apply failed -  -   Shadow field field_3694 was not located in the target class

### ISSUE THREAD

**Issue by Mixter213** [OroArmor/SlimeBlockInRedstoneTab#1]
Crash on startup.

[latest.log](https://github.com/OroArmor/SlimeBlockInRedstoneTab/files/5783095/latest.log) - Crash log

[Log.log](https://github.com/OroArmor/SlimeBlockInRedstoneTab/files/5783108/Log.log) - Game output log (copied from and pasted into text file )

Mods :
-fabric-api-0.28.4+1.16
-modmenu-1.14.13+build.19
-slimeblockredstone-2.0.0

Fabric loader - fabric-loader-0.10.8-1.16.4

**Comment by OroArmor** [comment]
Fixed!
